In [2]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

In [3]:
matrix = pd.read_csv('iris.data', usecols = [0, 1, 2, 3])
matrix

5.1  3.5  1.4  0.2
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
..   ...  ...  ...  ...
144  6.7  3.0  5.2  2.3
145  6.3  2.5  5.0  1.9
146  6.5  3.0  5.2  2.0
147  6.2  3.4  5.4  2.3
148  5.9  3.0  5.1  1.8

[149 rows x 4 columns]

In [6]:
for k in range(2,11):
    kmeans = KMeans(n_clusters = k).fit(matrix)
    print('k={0}'.format(k))
    print(kmeans.cluster_centers_)
    print(kmeans.labels_)

k=2
[[6.30103093 2.88659794 4.95876289 1.69587629]
 [5.00384615 3.35769231 1.56538462 0.29038462]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
k=3
[[5.9016129  2.7483871  4.39354839 1.43387097]
 [5.00408163 3.41632653 1.46530612 0.24489796]
 [6.85       3.07368421 5.74210526 2.07105263]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2 2
 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2 2
 0]
k=4
[[5.00408163 3.41632653 1.46530612 0.24489796]
 [6.2525     2.855      4.815      1.625     ]
 [5.53214286 2.63571429 3.96071429 1.22857143]
 [