In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random

In [21]:
df = pd.read_csv('iris.data', names=['para1', 'para2','para3','para4','genre'])
# df.columns(['para1', 'para2','para3','para4','genre'])

In [22]:
df = df.drop(columns="genre")

In [23]:
print(df)

     para1  para2  para3  para4
0      5.1    3.5    1.4    0.2
1      4.9    3.0    1.4    0.2
2      4.7    3.2    1.3    0.2
3      4.6    3.1    1.5    0.2
4      5.0    3.6    1.4    0.2
..     ...    ...    ...    ...
145    6.7    3.0    5.2    2.3
146    6.3    2.5    5.0    1.9
147    6.5    3.0    5.2    2.0
148    6.2    3.4    5.4    2.3
149    5.9    3.0    5.1    1.8

[150 rows x 4 columns]


In [24]:
matrix = np.array(df)
print(matrix.shape)
print(matrix)

(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

In [25]:
#Algorithm of Euclidian Distance
def Euclidian(p1, p2):
    if len(p1) != len(p2):
        return 0
    else:
        sumd = 0
        for i in range(len(p1)):
            sumd += np.square(p1[i] - p2[i])
        dist = np.sqrt(sumd)
        return dist

In [26]:
#Test for the algorithm
dist = Euclidian(matrix[0], matrix[1])
print(dist)

0.5385164807134502


In [27]:
k = 4
centroid = random.sample(list(matrix), k)
# centroid = [[4.4, 3. , 1.3, 0.2],[4.9, 3.1, 1.5, 0.1],[5.9, 3. , 5.1, 1.8],[6.6, 2.9, 4.6, 1.3]]
print(type(centroid))

<class 'list'>


In [28]:
# centroid1 = []
# centroid2 = []
# centroid3 = []
# centroid4 = []
# for point in matrix:
#     dis = []
#     for i in range(len(centroid)):
#         dis.append(Euclidian(point, centroid[i]))

#     #Classify
#     index_min = dis.index(min(dis))

#     if index_min == 0:
#         centroid1.append(list(point))
#     elif index_min == 1:
#         centroid2.append(list(point))
#     elif index_min == 2:
#         centroid3.append(list(point))
#     elif index_min == 3:
#         centroid4.append(list(point))
#     else:
#         print("Error")

# print(centroid1)
# print(centroid2)
# print(centroid3)
# print(centroid4)

In [29]:
length = len(centroid)
def new_cluster(k, length, centroid):
    cluster = []

    for _ in range(k):
        cluster.append([])

    for point in matrix:
        best_distance = -1
        best_index = -1
        for index in range(length):
            estimated_distance = Euclidian(point, centroid[index])
            if best_distance == -1:
                best_distance = estimated_distance
                best_index = index
            elif estimated_distance < best_distance:
                best_distance = estimated_distance
                best_index = index
        cluster[best_index].append(list(point))

#     print(cluster)
    return cluster

In [30]:
def centroids(cluster_part, length):
    new_centroid_each = [0.0] * length
    for point in cluster_part:
        for index in range(length):
            #calculate the sum
            new_centroid_each[index] = new_centroid_each[index] + point[index]
            
    #calculate the mean
    for index in range(length):
        new_centroid_each[index] /= len(cluster_part)
    return new_centroid_each

In [31]:
def newCentroid(cluster, length):
    new_centroid = []
    for cluster_part in cluster:
        new_centroid_each = centroids(cluster_part, length)
        new_centroid.append(new_centroid_each)
    return new_centroid

In [39]:
centroid_steps = [centroid]
loops = 20
limit_distance = 0.01
for step in range(loops):
    cluster = new_cluster(k, length, centroid)
    centroid = newCentroid(cluster, length)
    centroid_steps.append(centroid)


[[6.853846153846153, 3.0769230769230766, 5.715384615384615, 2.053846153846153], [5.370588235294117, 3.8, 1.5176470588235293, 0.2764705882352942], [5.88360655737705, 2.740983606557377, 4.388524590163935, 1.4344262295081966], [4.818181818181818, 3.2212121212121207, 1.436363636363636, 0.2272727272727273]]
